#+Title: Good Java Resources

I've been using Java since 2000 for a variety of tasks, mostly related
to software administration and maintenance. A common request from
co-workers and some of my geekier friends is a list of recommended
resources for Java training. I've built this list a couple of times, and
I keep losing the old lists, so I thought that I would put it on my wiki
so it would be a little more permanent. I hope that a few people find it
helpful. ## Dead-Tree Book Resources

-  [[http://www.amazon.com/exec/obidos/tg/detail/-/0131482114/qid=1120576682/sr=8-1/ref=sr_8_xs_ap_i1_xgl14/102-1756582-3155308?v=glance&s=books&n=507846][Just
   Java]]

   -  /The/ Java bible. No matter what you do with Java, you'll need
      this book eventually. Not only is it very informative, it is
      entertaining and very well written. It's one of those truly
      excellent technical books that you see so very rarely in a jungle
      of crap.

-  [[http://www.amazon.com/exec/obidos/tg/detail/-/0072226846/qid=1120577095/sr=8-1/ref=sr_8_xs_ap_i1_xgl14/102-1756582-3155308?v=glance&s=books&n=507846][Sun
   Certified Programmer & Developer for Java 2 Study Guide]]

   -  The only book you'll really need to become a Sun Certified Java
      Programmer. Also very well written.

-  [[http://www.amazon.com/exec/obidos/tg/detail/-/0596009208/qid=1120577361/sr=8-1/ref=sr_8_xs_ap_i1_xgl14/102-1756582-3155308?v=glance&s=books&n=507846][Head
   First Java]]

   -  I haven't actually read this book, but I've heard wonderful things
      about it from multiple sources, and it was written by the same
      authors of the previous bullet point. I look forward to reading
      the other books from the succesful
      [[http://headfirst.oreilly.com/][Head First series]].

-  [[http://www.amazon.com/exec/obidos/tg/detail/-/0130092290/qid=1120577790/sr=8-1/ref=sr_8_xs_ap_i1_xgl14/102-1756582-3155308?v=glance&s=books&n=507846][Core
   Servlets and Javaserver Pages]]

   -  A good book for learning the basics of JSP's and servlets. I
      recommend checking this book out from the library because it's a
      fairly quick read. Another cool thing about this book is that
      there are a lot of excerpts available at
      [[http://www.coreservlets.com/][http://www.coreservlets.com]].
      Definitely check out the web site if you're interested in this
      book.

** Online Book Resources

-  [[http://www.ibiblio.org/obp/thinkCS/java/english/][How To Think Like
   A Computer Scientist]]

   -  This is a good, free start to programming with Java.

-  [[http://www.mindview.net/Books/TIJ/][Thinking in Java]] - This is an
   *excellent* free book for programming in Java. It's quite possibly
   the best free programming book available for any language.

** Web Sites

-  [[http://javaranch.com/][JavaRanch]] - I *highly* recommend this web
   site if you are a beginning Java programmer. I feel that the
   following sections are particularly good:

   -  [[http://saloon.javaranch.com/cgi-bin/ubb/ultimatebb.cgi][Forum]]

      -  I received some great support from this forum on numerous
         occasions, but it was especially useful when I was studying for
         the SCJP test.

   -  [[http://www.javaranch.com/campfire.jsp][Campfire Stories]] -
      Tutorials and tips
   -  [[http://www.javaranch.com/books.jsp][Bunkhouse]] - The best place
      for unbiased reviews of Java books.
   -  [[http://www.javaranch.com/cattledrive.jsp][Cattle Drive]] - I am
      a former pupil in their Cattle Drive class, and found it to be a
      very good educational value for beginners.

-  [[http://mindprod.com/jgloss/jgloss.html][Roedy Green's Java &
   Internet Glossary]]

   -  His [[http://mindprod.com/jgloss/exception.html][exception page]]
      is my favorite place to go when I'm stuck on a particular error
      and need a little guidance. Also, it includes a treasure trove of
      documentation and tutorials to help you with most basic tasks.
      It's an absolutely essential resource.

*Note*: Please note that I linked to Amazon for all of the books listed
above, but I'm not getting a kickback for doing so. You should be able
to find a lot of these books at your local library, and they should all
be available from discount book sites such as
[[http://half.com/][half.com]]. Good luck and have fun!
