#+Title: How The Web Sees You 

On [[http://marketplace.publicradio.org/][Marketplace]] yesterday, there
was a great piece on how a lot of job-seekers are using social networks
to help them find new job. They focused on strategies that make it easy
for potential employers to find you based on relationships, and how
efficient that can be. Searching for a job has always been about *who
you know*, and *who those people know*. Hiring managers don't want to go
through the tedious and expensive work of finding new talent using
head-hunters or classified ads. They want to call someone that they
already know, or have a friend recommend someone. Social networks make
it easier to keep up with the people you know and connect with their
friends, making them a great job-finding tool. Social networking sites
aren't the only online tools that can help you with your job search.
*Blogs and mailing lists are also a great way to reach out to people*
with similar interests, even if you never meet them in person. For
example, there are a few technical blogs that I follow that are
well-written, informative, and indicative of an author with good
problem-solving skills. If I was looking to hire someone who had that
author's particular skills, then I'm likely to put that blog's author on
my short list. I feel the same way about mailing lists. It's difficult
to understate the importance of good problem-solving and communication
skills in the world of IT, and they're difficult to properly gauge in an
interview. If I see someone on a mailing list display these skills along
with strong technical skills, then putting them on my short-list is a
given. So it's obvious that I value good social networks in other
people. The problem is that I haven't been cultivating my networks as
well as I should be. Here's some of my issues: - *I have two different
blogs*. It's a long story as to why that's the case, but it doesn't do
much to help anyone find or learn about me. - *My Facebook page isn't
linked to my blog or my linkedin page, and vice-(vice?)-versa*. Someone
who knows me based on Facebook wouldn't know anything about my technical
skills, and someone who wanted to communicate with me via Facebook
wouldn't be able to do so if he or she only knew about my blog. - *My
Linkedin page is out-of-date*. Even though I'm not looking for a new job
right now (thank goodness), having an up-to-date profile can help both
myself and my friends. - *My blog is pretty empty*, which is especially
embarrassing when you consider that I've been writing blog articles in
one way or another for almost 6 years. The old articles are either lost,
or in a format that is difficult to convert into something Wordpress can
use. Also, I have a *lot* more stuff that I could be writing about. And
some of it might actually be worth reading by one or two people :)

So what can I do? Here are some actions that I think will help: - *Move
everything to a single blog*, and have that be a single,
publicly-accessible place for friends and professional resources to find
me. - *Link all of my sites together*, and make the associations very
obvious. - *Make a habit of updating my Linked profile* 3 or 4 times a
year. - *Move my good articles from my old blogs to my new one*. I'd
love to write more articles, but I don't think I'll make that a goal.
Obnoxious, forced articles are definitely worse than none at all.

It's a lot to do, which is probably why it isn't already done, but I
think it will pay off.
