#+Title: Gawker Password Breach - Lessons Learned 

I hate to admit it, but I was one of the millions of people whose Gawker
profile information was
[[http://www.guardian.co.uk/technology/2010/dec/29/gawker-hacking-gnosis-six-months][stolen
from a cracked server]]. What this means is that someone has my profile
information from Gawker, including my *e-mail address* and the *username
and password* that I used to authenticate so that I could leave comments
on Lifehacker.com.

The problem is that someone else can now try to log into a bunch of
other sites using either my e-mail address or Gawker ID /and/ my Gawker
password. I wish I could say that my Gawker ID's password was unique,
but I created it before I started using
[[http://keepass.info/][Keepass]] to manage all of my passwords. And to
make matters worse, my Gawker password is the one that I used to use on
all web sites that didn't contain "sensitive" or financial information.

Here's the good news:

-  I started using [[http://keepassx.org/][KeepassX]] and *Keepass*
   about 3 years ago to manage all of my internet user accounts, and
   *all of my "sensitive" accounts* (including e-mail, shopping, and all
   banking accounts) use a *much more secure password*.
-  All of my "sensitive" accounts have a *unique password*.
-  I have the user id and password for every web site with which I have
   registered over the last 3 years stored in my Keepass database.

The last point is important. Since almost all of my internet user
accounts are stored in Keepass, I used its *search feature* to look for
every account that uses my Gawker password. Within 15 minutes, I had
*changed my password on all of the sites that had formerly used my
Gawker password*. At the end of the day, Keepass had saved me a ton of
time and ensured that all of my accounts with the "bad" password were
accounted for.

So what are my lessons learned?

-  99.9% of web sites don't do a very good job of protecting user data,
   so I need to get in the habit of being much more paranoid about what
   I share online.
-  Every web account that I use *should at the very least have a unique
   password*. This can accomplished very easily using tools like
   Keepass.
-  Tools like Keepass and [[http://lastpass.com/][Lastpass]] are great,
   but they're not completely idiot-proof. Take sensible steps to secure
   your password database. For example, don't store your password
   database in a public place, use a strong master password, and use a
   [[http://keepass.info/help/base/keys.html][key file]].
-  If you have the opportunity to log into a web site using a common id
   such as your Facebook or Yahoo id, then you *should probably use it*.
   Facebook does a much better job securing your user information that
   most sites, so you are less likely to have your personal information
   stolen. Just make sure that you only use this sort of authentication
   on sites that don't contain "sensitive" information and that you have
   a relatively strong password for the common id.
-  If you're shopping online, you should *always* try to use a
   third-party checkout service like [[http://www.paypal.com/][Paypal]]
   or [[http://checkout.googe.com/][Google Checkout]]. The only
   exception to this rule is when you are using one of the "big"
   shopping sites, such as Amazon. "Bob's House of Tofu Jerky" probably
   shouldn't be in the web security business, so why are you trusting
   that company (and possibly a dozen others) with such private
   information? Paypal and Google do a much better job protecting your
   personal information.

Whew! Who knew that some day it would be so complicated to use the
internet?
