#+TITLE: Using Tor To Simplify Home Server Access

#+DATE: 2014-02-28 21:00

HA ha, this post isn't done yet :-) 

Tor hidden services have received a lot of press lately for being part
of the "dark web". You can only connect to them using a client that
can talk on the Tor network, so all users of a hidden service are
anonymous [1]. Also, hidden services use .onion addresses, which
aren't in DNS. This makes hidden services harder to find unless you
publicly publish the address.

Of course, when a person hears about this they tend to think of
cloak-and-dagger situations involving criminal masterminds, and hidden
services certainly are used by some criminals. However, the ability to
use the internet in a anonymous fashion is also terribly useful to
political dissidents around the world, journalists, and anyone else
that needs to connect to a beneficial online community without fear of
unjust reprisals.

So now that we've established that hidden services are not only for Bond
villains, we can take a step back and analyze hidden services for what
they truly are - *a terribly useful tool with lots of great
applications*. For example, in this blog post I'm going to show you how
you can use a hidden service to expose an SSH server running on your
home network quickly and easily. This server will have two benefits over
a regular SSH server:

1. We won't have to open any ports to the server in your router. [2]
2. Clients will only be able to connect to your server using a .onion
   address. They won't be able to use an IP address because your server
   will listening on the loopback interface only.

* Tor Hidden Services For Mere Mortals

When I was first learning about Tor, the concept of a hidden service was
terribly mysterious to me. It seemed as though most hidden services were
web servers that I had to access using a Tor-ified web browser, but it
also appeared that I could connect to an IRC chat room or git server
using a .onion address. So which part is tor and which part is the
service?

A hidden service is simply a service that runs behind a Tor daemon.
That's it. You configure the Tor daemon to forward traffic to the
service and it takes care of the rest. The service behind Tor can be
pretty much anything - HTTP, SMTP, IRC, you name it.

Oh, I forgot part two - you have to use a .onion address to access the
hidden service. There is no part 3.

The client side is a tiny bit trickier, but not much. To access a hidden
service, you have to "Tor-ify" your client. Tor-ifying means that you
have to configure your client to talk through a SOCKS proxy. This can be
very easy (like using the Tor Browser Bundle to browse web sites) or
much more complex, depending on the type of client.

We're going to be Tor-ifying an SSH client, which is a fairly simple
thing to do on most Unix-like systems.

Now of course there's a lot more to hidden services than what I have
described here. For example, how does the Tor daemon listen for new
connections? How does my client know how to connect to the .onion
address? What are the network vulnerabilities of running Tor on a
server?

We'll talk about some of these questions later, For now, I hope that
this general overview has helped clear up some confusion.

* Configuring SSH As A Hidden Service

In this example, I'm going to configure an "hidden" SSH server on a
Raspberry Pi running on my home network. This particular server is
running Raspbian 7.2.

#+BEGIN_QUOTE
  *note*

  Please note that while this process may be Debian-specific, you can
  use similar steps on almost any Unix-like system.
#+END_QUOTE
