#+TITLE: Review Of "Just F*cking Ship"

#+DATE: 2015-2-9 19:00

-  [[https://unicornfree.com/just-fucking-ship]]

What I liked about this book is that it is full of lots of good
information There are some very good tips and real world advice on
completing a technical project on time.

What I didn't like about this book is that this good advice was buried
within an annoying style of prose that felt much more like a sales pitch
than a instructional book. I never quite got used to this style, but I
also admit that it was probably intended by the author and appreciated
by a lot of its readers. It just didn't fit my subjective tastes very
well.

While I'm on the subject, here's a couple more things about purchasing
this book that I wish were different:

-  As of 1/30/15, there is no epub version of this book available. The
   author states that this is something that she will release soon.
-  I was placed on an advertising mailing list after buying this book.
   This was a bit surprising to me because that had never happened to me
   before after purchasing an e-book from an author. I also don't
   remember being asked if I could opt-out when purchasing the book.
   This sort of marketing is something I really don't enjoy.

And now back to something more positive. If you find yourself failing
over and over again when it comes to releasing your projects, check this
book out. Even with it's rough edges you'll be happy that you did. Short
version - *3/5 stars*.
