#+TITLE: Emacs Cheat Sheet


* Screen navigation

- Quit
    - `C-x C-c`
- Move down a screen
    - `C-v`
- Move up a screen
    - `M-v`
- forward one char
    - `C-f`
- backwards one char
    - `C-b`
- up one line
    - `C-p`
- down one line
    - `C-n`
- forward one word
    - `M-f`
- Backwards one word
    - `M-b`
- Move to the other window
    - `C-x o`
- Move forward one page
    -  `C-v`
- Move backwards one page
    -  `M-v`
- Reset page around cursor with it at the center.
    -  `C-l`
- Move forward one word
    -  `M-f`
- Move backwards one word
    -  `M-b`
- Move to the beginning of a line.
    -  `C-a`
- Move to the beginning of a sentence.
    -  `M-a`
- Move to the end of a line.
    -  `C-e`
- Move to the end of a sentence.
    -  `M-e`
- Move to the beginning of the document
    -  `M-<` - Move
    - Please note that you also need to press the shift key since `<` is above
      the `,` key.
- Move to the end of the document
    -  `M->` - Move
-  Show only one window
    -  `C-x 1`
-  Horizontally split the current window
    -  `C-x 2`
-  Vertically split the current window
    -  `C-x 3`

Moving around one line at a time:

#+BEGIN_EXAMPLE
                      Previous line, C-p
                              :
                              :
Backward, C-b .... Current cursor position .... Forward, C-f
                              :
                              :
                        Next line, C-n
#+END_EXAMPLE
 
* Search

- Incremental Search
    - `C-s`
    - To find the next match just keep pressing `C-s`

* File Management

- Creating a new file
    - Find it `(C-x C-f)`
    - Type in the location where you want to save it.
- Saving a file
    - `C-x C-s`

** Registers

Registers are good for quickly storing and finding all kinds of things, but I
mostly use them to open files that I use a lot. For example, I can put the 
following in my `.emacs` file:

#+BEGIN_EXAMPLE
    ; Org index
    (set-register ?i (cons 'file "c:/td/gtd/org/index.org"))
    ; .emacs file
    (set-register ?e (cons 'file "~/.emacs"))
#+END_EXAMPLE

…and then open the files like this:
 
`C-x r j i`

`C-x r j e` 

* Text Management

- Auto wrap a line by adding a carriage return
    - Similar to `gqip` in Vim
    - `M-q`
- Selecting Text
    - Simply go to the beginning, press `C-Space` and then navigate to the end
      position.
    - This is a lot like a visual select in Vim.
- Copy Text
    - `M-w`
- Cut Text
    - `C-w`

** CUA Mode

CUA Mode allows you to use C-c and C-v when you have selected text. Here’s more
information:

- http://www.emacswiki.org/emacs/CuaMode

…and here’s what I added to me .emacs file:

#+BEGIN_EXAMPLE
    (cua-mode t)
    (setq cua-auto-tabify-rectangles nil) ;; Don't tabify after rectangle commands
    (transient-mark-mode 1) ;; No region when it is not highlighted
    (setq cua-keep-region-after-copy t) ;; Standard Windows behavior
#+END_EXAMPLE

* Scripting

** Interrogating A Variable VAles

If you want to find out the current value of a variable, just type the
following:

#+BEGIN_EXAMPLE
    C-h v <var name>
#+END_EXAMPLE

For example:

#+BEGIN_EXAMPLE
    C-h v org-agenda-files
#+END_EXAMPLE

* Misc

** Remove Version Page On Startup

[[#+BEGIN_EXAMPLE
    ; http://askubuntu.com/a/4824
    (setq inhibit-startup-screen t)
    (add-hook 'emacs-startup-hook
      (lambda () (delete-other-windows)) t)
#+END_EXAMPLE

** Change The Default Web Browser

This is all I had to add to my `.emacs` file on my Windows 7 machine to
start using Firefox instead of IE:

#+BEGIN_EXAMPLE
    (setq browse-url-browser-function 'browse-url-firefox)
#+END_EXAMPLE

** Show Line Numbers

#+BEGIN_EXAMPLE
    M-x linum-mode
#+END_EXAMPLE

** Toggle Word Wrap

This is similar to the =:set nowrap= command in Vim, except it toggles
the option:

#+BEGIN_EXAMPLE

M-x toggle-truncate-lines

#+END_EXAMPLE
