#+TITLE: Favorite Quotes

* 2017
** 1/25/2017

Tim Bray, from his blog post [[https://www.tbray.org/ongoing/When/201x/2017/01/22/Womens-March][The Women's March]] about the worldwide
protest of the new Trump administration that occurred the day after
his inauguration:

#+BEGIN_QUOTE -r

I think it's obvious. A bunch of reasonable people, led by women,
needed to shout out and reassure each other that they weren't crazy
because they were horrified at a nouveau regime that's crude,
threatening, ignorant, oligarchic, reactionary, childish, corrupt,
bigoted, thin-skinned, offensive, and oozes appallingly bad taste.

#+END_QUOTE

* 2016
** 12/16/2016

This is from the intro to the [[http://www.danagould.com/the-dog-that-caught-the-car/][The Dog That Caught The Car]] episode of
[[http://www.danagould.com/dgh/][The Dana Gould Hour]] podcast. Dana was referring to the "media
misinformation bubble" that he lives in:

#+BEGIN_QUOTE -r

There are too are too many people in this country talking past each
other. The internet, which was supposed to unite us, has divided us
farther. And I am of the belief that the election of someone like
Donald Trump is in part a direct result of an electorate too far
ensconced in their own ideological readouts to communicate even the
simplest disagreements constructively. And that has to stop.

#+END_QUOTE

** 12/01/2016

Cathy O'Neil on the [[https://trackchanges.postlight.com/podcast-39-cathy-oneil-on-weapons-of-math-destruction-ccc7fbcb0b6d#.kr3vhdhaf][Weapons Of Math Destruction]] episode of the [[https://trackchanges.postlight.com/][Track
Changes]] podcast. Earlier in the podcast she discusses her love of the
"purity" of math and her disappointment after learning that
Credit-Default-Swaps were being over-rated by ratings agencies in
2007 (at *16:57*):

#+BEGIN_QUOTE -r

Math wasn't the problem actually. It wasn't that we had the *wrong*
models, it's that we really don't care...about the truth, that it's
become a political thing.

#+END_QUOTE

** 11/03/2016

Dana Gould on the [[http://www.danagould.com/the-ghost-mr-halloweenery/][The Ghost & Mr. Halloweenery episode]] of [[http://www.danagould.com/dgh/][The Dana
Gould Hour]] podcast at *3:16:40* speaking to legendary makeup artist
Rick Baker on how their "weird little hobbies" have lead to fulfilling
careers:

#+BEGIN_QUOTE -r

The only thing that I've noticed in my storied career is that things
lead to things, and if you do things and make things, things come of
it. And if you don't do things and don't make things then things don't
come of it.

#+END_QUOTE

The above quote from Dana Gould also reminds me of the ending of the book
[[http://goraina.com/books/smile/][Smile]] by Raina Telgemeier:

#+BEGIN_QUOTE

My life didn't magically turn perfect after that. I didn't "get the
guy" as they say. [...] Instead, I threw my passion into things I
enjoyed, rather than feeling sorry for myself. I realized that I had
been letting the way I looked on the outside affect how I felt on the
inside. But the more I focused on my interests, the more it brought
out things I liked about myself. And that affected the way *other*
people saw me.

#+END_QUOTE

-----

Joel Hodgson on the [[http://www.danagould.com/the-ghost-mr-halloweenery/][The Ghost & Mr. Halloweenery episode]] of [[http://www.danagould.com/dgh/][The Dana
Gould Podcast]] at *3:08:31* on why he temporarily retired from show
business immediately after turning down a lucrative sitcom offer
(after he'd done Letterman and SNL):

#+BEGIN_QUOTE -r

Ultimately at the end of the day all you have to bargain with is
yourself, and kindof like either I'm gonna do this or I'm not gonna do
this but you have no real leverage outside of that, and I think, I
just wasn't feeling it, and I knew that I'd feel bad if I went and did
this kindof hollow [sitcom role].

#+END_QUOTE

** 2/8/2016

James Baldwin's advice on *why writers write* from [[http://www.amazon.com/Writers-Chapbook-George-Plimpton/dp/0670815659/?tag=braipick-20][The Writer's
Chapbook]] (via [[https://www.brainpickings.org/2016/02/08/james-baldwin-advice-on-writing/][Brain Pickings]]):

#+BEGIN_QUOTE -r

Something that irritates you and won’t let you go. That’s the anguish
of it. Do this book, or die. You have to go through that. Talent is
insignificant. I know a lot of talented ruins. Beyond talent lie all
the usual words: discipline, love, luck, but most of all, endurance.

#+END_QUOTE

* 2015
** 11/27/2015

Michael Nygard in his [[http://www.michaelnygard.com/blog/2015/10/software-eats-the-world/][Software Eats The World]] article:

#+BEGIN_QUOTE -r
    Back in 2011, Marc Andreessen said ”[[http://www.wsj.com/articles/SB10001424053111903480904576512250915629460][software is eating the world]]”.
    There’s no reason to think that’s going to slow down soon. And as
    software eats the world, work becomes tech work.
#+END_QUOTE

** 08/12/15

Les Orchard, [[http://blog.lmorchard.com/2015/07/22/the-verge-web-sucks][The Verge's Web Sucks]]

#+BEGIN_QUOTE -r
    "But, is it ultimately a good idea to optimize for these icebergs that
    consist of the tiny bit we came for, perched atop a great big submerged
    intelligence gathering apparatus assembled on-demand from a consortium of
    marketing & analytics firms?"
#+END_QUOTE

I have to say that this is my favorite article on technology so far this year.
I highly recommend it.

** 08/06/15

Dana Gould, [[https://soundcloud.com/laughspin/just-for-laughs-dana-gould-keynote-address][2015 Just For Laughs Keynote Address]] (15:22):

#+BEGIN_QUOTE -r
    "We are in a world where everything has been reduced to a competition,
    because in competition there is drama, and drama is compelling and when
    something is compelling people watch it and when people watch it you can sell
    advertising. And if you're not selling something or buying something why the
    fuck are you awake?!? That's why the news is no longer what happened, the
    news is *who won*."
#+END_QUOTE

** 07/22/15

Geneva Reed-Veal, [[https://en.wikipedia.org/w/index.php?title%3DDeath_of_Sandra_Bland][Sandra Bland]]'s mother, from her [[http://www.democracynow.org/2015/7/22/i_will_light_you_up_new][daughter's funeral]]
 
#+BEGIN_QUOTE -r
    "Let’s be for real. That was my baby. She wasn’t my convict. She wasn’t the
    suspect. She was my baby. And it would behoove y’all to think about what you
    all were doing at her age. So some of the stuff that’s in the news is true,
    some of the stuff that’s in the news is not. But the real issue here is
    something occurred that is going to change the world."
#+END_QUOTE

** 07/01/15

Gennifer Hutchinson, [[https://twitter.com/GennHutchison/status/616032089423548416][tweet]]

#+BEGIN_QUOTE -r
    "If you want to make it as a TV writer, don't be a jerk. Make it so people
    want to spend all day in a room with you. Also a good life rule."
#+END_QUOTE

** 04/06/15

Gabriel García Márquez, [[http://www.brainpickings.org/2015/04/06/marquez-favorite-books/][Gabriel García Márquez’s Formative Reading List: 24 Books That Shaped One of Humanity’s Greatest Writers]]

#+BEGIN_QUOTE -r
    "Life is not what one lived, but what one remembers and how one remembers
    it in order to recount it."
#+END_QUOTE

** 01/29/15

Louis C K, [[https://louisck.net/purchase/live-at-the-comedy-store][Live At The Comedy Store]]:

#+BEGIN_QUOTE -r
    "Self love is a good thing, but *self awareness* is more important. You need
    to once in a while go 'uh, I'm kind of an asshole'. You have to have that
    thought once in a while or you're a psychopath."
#+END_QUOTE

* 2014
** 10/27/14
    
Robert X. Cringely, [[http://www.cringely.com/2014/10/27/fix-ibm/][How To Fix IBM]]:
   
#+BEGIN_QUOTE -r
    "History has shown that when a company trashes its quality, neglects its
    customers, and makes earnings its only priority – bad things happen. Over the
    last 50 years, the USA has lost many industries this way. If IBM does not get
    serious about quality its survival will be at risk."
#+END_QUOTE

** 10/10/14
    
Kailash Satyarthi regarding his [[http://news-beta.slashdot.org/story/14/10/10/1328236/2014-nobel-peace-prize-awarded-to-kailash-satyarthi-and-malala-yousafzay][fight against child slavery and illiteracy in India]]:

#+BEGIN_QUOTE -r
    "Satyarthi estimates that 60 million children in India, or 6 percent of the
    population, are forced into work. This, he believes, has nothing to do with
    parental poverty, illiteracy or ignorance. Above all, children are enslaved
    because employers benefit by getting their labour for free or for a pittance."
#+END_QUOTE

** 10/03/14

The Jen Meyers Report, [[http://tinyletter.com/jenmyers/letters/maybe-everything-that-dies-someday-comes-back][October 3 2014]]:

#+BEGIN_QUOTE -r
    Americans may not like to talk about class divisions, but there is at least
    one, and it’s between those who never imagine not getting what they’ve been
    taught they deserve and those who know that no matter what they do, nothing is
    guaranteed.
#+END_QUOTE
    
** 09/10/14
    
[[http://mentalpod.libsyn.com/episode-188-ask-erika-holmes-mft][Mental Illness Happy Hour -188]], a 
"Happy Moment" message from a listener name Sherlock (1:47:25):

#+BEGIN_QUOTE -r
    Don't be afraid of (the) stigma (of mental illness) - fight it. The
    ignorance, denial and prejudice surrounding mental and addictive disorders
    kills people. It's in the news almost daily.
     
    The simplest way to fight it is to seek services. The next step is to be
    open about your own struggles. The next step is to advocate - do what you
    can.
#+END_QUOTE
  
** 08/12/14
    
Marc Maron from the [[http://www.wtfpod.com/podcast/episodes/remembering_robin_williams][Robin Williams interview]]:

#+BEGIN_QUOTE -r
    Show business is "A community of bitter people aspiring to something, and
    they're children because what they're aspiring to is ridiculous."
#+END_QUOTE

** 07/22/14

This is stolen from [[http://qblog.aaronsw.com][Arron Swartz's quote blog]]:

[[http://www.nobelprize.org/nobel_prizes/literature/laureates/1950/russell-lecture.html|Bertrand Russell]] 

#+BEGIN_QUOTE -r
    "The devil has many forms, some designed to deceive the young, some
    designed to deceive the old and serious. If it is the devil that tempts the
    young to enjoy themselves, is it not, perhaps, the same personage that
    persuades the old to condemn their enjoyment? And is not condemnation perhaps
    merely a form of excitement appropriate to old age? And is it not, perhaps, a
    drug which - like opium - has to be taken in continually stronger doses to
    produce the desired effect? Is it not to be feared that, beginning with the
    wickedness of the cinema, we should be led step by step to condemn the opposite
    political party, dagoes, wops, Asiatics, and, in short, everybody except the
    fellow members of our club? And it is from just such condemnations, when
    widespread, that wars proceed. I have never heard of a war that proceeded from
    dance halls."
#+END_QUOTE

* ???

** Wait Wait Don't Tell Me

#+BEGIN_QUOTE -r
    "After binging for a decade, with money we don't have, President Obama decided
    the only way out of the crisis is to spend almost a trillion dollars we don't
    have either.  This is like curing a hangover by buying a distillery.  The
    Republicans don't like it; they don't like spending money on anything unless it
    blows up, like Iraq, or Merill Lynch."
#+END_QUOTE
