#+TITLE: Favorite Quotes

* 08/12/15

Les Orchard, [[http://blog.lmorchard.com/2015/07/22/the-verge-web-sucks/|The Verge's web sucks]]: 

    "But, is it ultimately a good idea to optimize for these icebergs that
    consist of the tiny bit we came for, perched atop a great big submerged
    intelligence gathering apparatus assembled on-demand from a consortium of
    marketing & analytics firms?"

I have to say that this is my favorite article on technology so far this year.
I highly recommend it.

* 08/06/15

Dana Gould, [[https://soundcloud.com/laughspin/just-for-laughs-dana-gould-keynote-address|Just For Laughs 2015 Keynote Address]] (15:22):

    "We are in a world where everything has been reduced to a competition,
    because in competition there is drama, and drama is compelling and when
    something is compelling people watch it and when people watch it you can sell
    advertising. And if you're not selling something or buying something why the
    fuck are you awake?!? That's why the news is no longer what happened, the
    news is -who won-."

* 07/22/15

Geneva Reed-Veal, [[https://en.wikipedia.org/w/index.php?title=Death_of_Sandra_Bland&redirect=no|Sandra Bland]]'s mother, from her [[http://www.democracynow.org/2015/7/22/i_will_light_you_up_new|daughter's funeral]]:
 
    "Let’s be for real. That was my baby. She wasn’t my convict. She wasn’t the
    suspect. She was my baby. And it would behoove y’all to think about what you
    all were doing at her age. So some of the stuff that’s in the news is true,
    some of the stuff that’s in the news is not. But the real issue here is
    something occurred that is going to change the world."

* 07/01/15

Gennifer Hutchinson, [[https://twitter.com/GennHutchison/status/616032089423548416|Tweet]]:

    "If you want to make it as a TV writer, don't be a jerk. Make it so people
    want to spend all day in a room with you. Also a good life rule."

* 04/06/15

Gabriel García Márquez, [[http://www.brainpickings.org/2015/04/06/marquez-favorite-books/|Gabriel García Márquez’s Formative Reading List: 24 Books That Shaped One of Humanity’s Greatest Writers]]:

    "Life is not what one lived, but what one remembers and how one remembers
    it in order to recount it."

* 01/29/15

Louis C K, [[https://louisck.net/purchase/live-at-the-comedy-store|Live At The Comedy Store]]:

    "Self love is a good thing, but -self awareness- is more important. You need
    to once in a while go 'uh, I'm kind of an asshole'. You have to have that
    thought once in a while or you're a psychopath."

* 10/27/14
    
Robert X. Cringely, [[http://www.cringely.com/2014/10/27/fix-ibm/|How To Fix IBM]]:
   
    "History has shown that when a company trashes its quality, neglects its
    customers, and makes earnings its only priority – bad things happen. Over the
    last 50 years, the USA has lost many industries this way. If IBM does not get
    serious about quality its survival will be at risk."

* 10/10/14
    
Kailash Satyarthi regarding his [[http://news-beta.slashdot.org/story/14/10/10/1328236/2014-nobel-peace-prize-awarded-to-kailash-satyarthi-and-malala-yousafzay|fight against child slavery and illiteracy in India]]:

    "Satyarthi estimates that 60 million children in India, or 6 percent of the
    population, are forced into work. This, he believes, has nothing to do with
    parental poverty, illiteracy or ignorance. Above all, children are enslaved
    because employers benefit by getting their labour for free or for a pittance."

* 10/03/14

The Jen Meyers Report, [[http://tinyletter.com/jenmyers/letters/maybe-everything-that-dies-someday-comes-back|October 3 2014]]:

    Americans may not like to talk about class divisions, but there is at least
    one, and it’s between those who never imagine not getting what they’ve been
    taught they deserve and those who know that no matter what they do, nothing is
    guaranteed.
    
* 09/10/14
    
[[http://mentalpod.libsyn.com/episode-188-ask-erika-holmes-mft|Mental Illness Happy Hour -188]], a 
"Happy Moment" message from a listener name Sherlock (1:47:25):

    Don't be afraid of (the) stigma (of mental illness) - fight it. The
    ignorance, denial and prejudice surrounding mental and addictive disorders
    kills people. It's in the news almost daily.
     
    The simplest way to fight it is to seek services. The next step is to be
    open about your own struggles. The next step is to advocate - do what you
    can.
  
* 08/12/14
    
Marc Maron from the [[http://www.wtfpod.com/podcast/episodes/remembering_robin_williams|Robin Williams interview]]:

    Show business is "A community of bitter people aspiring to something, and
    they're children because what they're aspiring to is ridiculous."

* 07/22/14
    
** 08:11

This is stolen from [[http://qblog.aaronsw.com|Arron Swartz's quote blog]]:

[[http://www.nobelprize.org/nobel_prizes/literature/laureates/1950/russell-lecture.html|Bertrand Russell]] 

    "The devil has many forms, some designed to deceive the young, some
    designed to deceive the old and serious. If it is the devil that tempts the
    young to enjoy themselves, is it not, perhaps, the same personage that
    persuades the old to condemn their enjoyment? And is not condemnation perhaps
    merely a form of excitement appropriate to old age? And is it not, perhaps, a
    drug which - like opium - has to be taken in continually stronger doses to
    produce the desired effect? Is it not to be feared that, beginning with the
    wickedness of the cinema, we should be led step by step to condemn the opposite
    political party, dagoes, wops, Asiatics, and, in short, everybody except the
    fellow members of our club? And it is from just such condemnations, when
    widespread, that wars proceed. I have never heard of a war that proceeded from
    dance halls."

* ???

** Wait Wait Don't Tell Me

    "After binging for a decade, with money we don't have, President Obama decided
    the only way out of the crisis is to spend almost a trillion dollars we don't
    have either.  This is like curing a hangover by buying a distillery.  The
    Republicans don't like it; they don't like spending money on anything unless it
    blows up, like Iraq, or Merill Lynch."
