c#+TITLE: ffmpeg Cheat Sheet

* Converting To TS Files

Look here:

- https://trac.ffmpeg.org/wiki/Concatenate#protocol

** H264 -> TS

#+BEGIN_SRC sh

ffmpeg -i input1.mp4 -c copy -bsf:v h264_mp4toannexb -f mpegts intermediate1.ts

#+END_SRC

* Concatenating H264 Files

Look here:

- https://trac.ffmpeg.org/wiki/Concatenate#protocol

First convert the H264 files to TS files using the command above. Then
concatenate them like this:

#+BEGIN_SRC sh

ffmpeg -i "concat:intermediate1.ts|intermediate2.ts" -c copy -bsf:a aac_adtstoasc output.mp4

#+END_SRC

* Cutting Clips

This is stolen from here:

- http://superuser.com/a/141343/78501

First, if you're working with an H264 file you should converti it into
a TS file. Then you can do this:

"The following would clip the first 30 seconds, and then clip
everything that is 10 seconds after that:"

#+BEGIN_SRC sh

ffmpeg -i input.ts -ss 00:00:30.0 -c copy -t 00:00:10.0 output.ts

#+END_SRC

* Encoding Examples

** Youtube

Naturally, this assumes that you're working with a TS file.

- https://www.virag.si/2015/06/encoding-videos-for-youtube-with-ffmpeg/

#+BEGIN_SRC sh

ffmpeg -i <input file> -codec:v libx264 -crf 21 -bf 2 -flags +cgop -pix_fmt yuv420p -codec:a aac -strict -2 -b:a 384k -r:a 48000 -movflags faststart <output_name>.mp4

#+END_SRC
* Recording Screencasts

Please note the screen size and change it based on your monitor. This
value below works well with my laptop's built-in screen:

#+BEGIN_SRC sh

ffmpeg -video_size 1366x768 -framerate 25 -f x11grab -i :0.0+0,0 -f alsa -ac 2 -i pulse output.mkv

#+END_SRC

Also please note that I'm running Debian Linux. This command is slightly
different based on your OS, Linux distribution or season. 
* Flipping Videos 180 Degrees

I'm having a lot of problems doing this in ffmpeg, so I punt to
Handbrake instead:

- [[file:Handbrake_Cheat_Sheet.org::*Flipping%20Videos%20180%20Degrees][Flipping Videos 180 Degrees]]
* Stripping The Audio Portion From An MP4

First, see what format the audio track uses:

#+BEGIN_SRC sh
ffmpeg -i input.mp4 2>&1 | grep Stream
#+END_SRC

If the audio file use the AAC format then strip it out like so:

#+BEGIN_SRC sh
ffmpeg -i input.mp4 -vn -acodec copy output.aac
#+END_SRC

* Converting AAC Files To MP3

#+BEGIN_SRC sh
ffmpeg -i ./input.aac -c:a libmp3lame -ac 2 -q:a 2 output.mp3
#+END_SRC
